on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: npm ci
      - run: npm run prettier:check
      - run: npm run json:validate

      - name: Set up Github Packages
        # if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          distribution: "temurin"
          java-version: "17"
          cache: maven
          server-id: github  # matches distributionManagement in pom.xml
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Publish to Github Packages
        # if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          DATE_FORMATTED=`date +%d%m%Y`
          GIT_SHA_SHORT=`echo $GITHUB_SHA | cut -c1-7`
          NEW_VERSION=${DATE_FORMATTED}.${GIT_SHA_SHORT}
          mvn versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the automatically generated GITHUB_TOKEN
