on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.1
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier:check
      - run: pnpm json:validate

      - name: Set up Java
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Validate Maven build
        if: ${{ github.event_name == 'pull_request' }}
        run: mvn verify

      - name: Set up Github Packages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: "temurin"
          java-version: "21"
          cache: maven
          server-id: github # matches distributionManagement in pom.xml
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Publish to Github Packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          DATE_FORMATTED=`date +%d%m%Y`
          GIT_SHA_SHORT=`echo $GITHUB_SHA | cut -c1-7`
          NEW_VERSION=${DATE_FORMATTED}.${GIT_SHA_SHORT}
          mvn versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the automatically generated GITHUB_TOKEN
